/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OffresRouteImport } from './routes/offres'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LieuxIndexRouteImport } from './routes/lieux/index'
import { Route as LieuxSlugRouteImport } from './routes/lieux/$slug'
import { Route as ApiLatestPlacesRouteImport } from './routes/api/latest-places'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OffresRoute = OffresRouteImport.update({
  id: '/offres',
  path: '/offres',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LieuxIndexRoute = LieuxIndexRouteImport.update({
  id: '/lieux/',
  path: '/lieux/',
  getParentRoute: () => rootRouteImport,
} as any)
const LieuxSlugRoute = LieuxSlugRouteImport.update({
  id: '/lieux/$slug',
  path: '/lieux/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLatestPlacesRoute = ApiLatestPlacesRouteImport.update({
  id: '/api/latest-places',
  path: '/api/latest-places',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/offres': typeof OffresRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/latest-places': typeof ApiLatestPlacesRoute
  '/lieux/$slug': typeof LieuxSlugRoute
  '/lieux/': typeof LieuxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/offres': typeof OffresRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/latest-places': typeof ApiLatestPlacesRoute
  '/lieux/$slug': typeof LieuxSlugRoute
  '/lieux': typeof LieuxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/offres': typeof OffresRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/latest-places': typeof ApiLatestPlacesRoute
  '/lieux/$slug': typeof LieuxSlugRoute
  '/lieux/': typeof LieuxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/offres'
    | '/sitemap.xml'
    | '/api/latest-places'
    | '/lieux/$slug'
    | '/lieux/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/offres'
    | '/sitemap.xml'
    | '/api/latest-places'
    | '/lieux/$slug'
    | '/lieux'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/offres'
    | '/sitemap.xml'
    | '/api/latest-places'
    | '/lieux/$slug'
    | '/lieux/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  OffresRoute: typeof OffresRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiLatestPlacesRoute: typeof ApiLatestPlacesRoute
  LieuxSlugRoute: typeof LieuxSlugRoute
  LieuxIndexRoute: typeof LieuxIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offres': {
      id: '/offres'
      path: '/offres'
      fullPath: '/offres'
      preLoaderRoute: typeof OffresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lieux/': {
      id: '/lieux/'
      path: '/lieux'
      fullPath: '/lieux/'
      preLoaderRoute: typeof LieuxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lieux/$slug': {
      id: '/lieux/$slug'
      path: '/lieux/$slug'
      fullPath: '/lieux/$slug'
      preLoaderRoute: typeof LieuxSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/latest-places': {
      id: '/api/latest-places'
      path: '/api/latest-places'
      fullPath: '/api/latest-places'
      preLoaderRoute: typeof ApiLatestPlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  OffresRoute: OffresRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiLatestPlacesRoute: ApiLatestPlacesRoute,
  LieuxSlugRoute: LieuxSlugRoute,
  LieuxIndexRoute: LieuxIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
